-- Erstelle locations Tabelle für PLZ-Suche
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zip_code TEXT NOT NULL,
  city VARCHAR(255) NOT NULL,
  canton VARCHAR(2) NOT NULL,
  region_code VARCHAR(10) NOT NULL, -- z.B. "CH01" oder "PR-REG CH1"
  bfs_number INTEGER, -- Gemeinde-Nummer
  
  -- Index für schnelle Suche
  CONSTRAINT locations_zip_city_key UNIQUE (zip_code, city)
);

CREATE INDEX IF NOT EXISTS idx_locations_zip ON locations(zip_code);
CREATE INDEX IF NOT EXISTS idx_locations_city ON locations(city);

